todo/urls.py
from django.urls import path
from .import views

app_name = 'todo'

urlpatterns = [
    path('', views.homePage, name='home'),
    path('done/<int:todo_id>', views.doneTodo, name='done'),
    path('update/<pk>', views.UpdateTodoView.as_view(), name='update'),
    path('delete/<int:todo_id>', views.deleteTodo, name='delete'),
]

todoApp/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls', namespace='todo')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

todo/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
	PRIORITIES = (
		('red', 'RED'),
		('green', 'GREEN'),
		('yellow', 'YELLOW'),
		)
	title = models.CharField('Title',max_length=200)
	text = models.CharField('Text', max_length=800,blank=True)
	date = models.DateTimeField('Time', auto_now_add=True)
	done = models.BooleanField('Done ?', default=False)
	priority = models.CharField('Priority',max_length=50,choices=PRIORITIES, blank=True)

	def __str__(self):
		return self.title

	class Meta:
		ordering = ['-id']

todo/forms.py
from django import forms
from .models import Todo

class TodoAddForm(forms.ModelForm):

	class Meta:
		model = Todo 
		fields = '__all__'
		exclude = ('done',)

todo/views.py
from django.shortcuts import render,redirect 
from django.urls import reverse
from django.http import HttpResponseRedirect
from .models import Todo
from django.views.generic.edit import UpdateView

from .forms import TodoAddForm

# Create your views here.
def homePage(request):
	if request.method == 'POST':
		form = TodoAddForm(request.POST)
		if form.is_valid():
			form.save()
	else:
		form = TodoAddForm()

	todos = Todo.objects.filter(done=False)
	doned_todos = Todo.objects.filter(done=True)
	for todo in todos:
		if todo.priority == 'red':
			todo.priority = 'list-group-item-warning'
		elif todo.priority == 'green':
			todo.priority = 'list-group-item-success'
		elif todo.priority == 'yellow':
			todo.priority = 'list-group-item-info'
	context = {
		'todos':todos,
		'addform':form,
		'doned_todos':doned_todos
	}
	return render(request, 'index.html', context)

def doneTodo(request,todo_id):
	todo = Todo.objects.get(id=todo_id)
	todo.done = True
	todo.save()
	if todo:
		return redirect('todo:home')
	return render(request,'index.html')

def deleteTodo(request,todo_id):
	todo = Todo.objects.get(id=todo_id)
	todo.delete()
	return redirect('todo:home')

class UpdateTodoView(UpdateView):
	model = Todo
	fields = ['title', 'text','priority']
	template_name = 'update.html'
	success_url = '/'

templates/index.html
                        б<!doctype html>
{% load crispy_forms_tags %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <title>JDU Student's plan</title>
  </head>
<script>
if ( window.history.replaceState ) {
 window.history.replaceState( null, null, window.location.href );
} офмдщту мф ьгтшткщ ешд

</script>
  <body onload="TimeStart()">
<section class="mt-5">
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header bg-info">
            <h3 class="d-inline-block">Bajariladigan ishlar</h3><button type="button" class="btn btn-primary d-inline-block" id="add" data-toggle="modal" data-target="#exampleModal"><i class="fas fa-plus"></i></button>
          </div>
 
          <div class="card-body">
            {% for todo in todos %}
       
            <div class="todos">
              <div class="container">
                <div class="row">
                  <div class="col-sm-9">
                    <ul class="list-group">

                      <li class="list-group-item {{todo.priority}} mt-3" id="todo">
                        <h5>{{todo.title}}</h5>
                        <h6>{{todo.text}}</h6>
                      </li>

                    </ul>
                  </div>
                  <div class="col-sm-3">
                    <div class="content">
                    <div class="m-2">
                      <a href="{% url 'todo:done' todo.id %}">
                        <button type="submit" class="btn btn-primary"><i class="fas fa-check"></i></button>
                        </a>                
                    </div>
                    <div class="m-2">
                      <a href="{% url 'todo:update' todo.id %}">
                      <button type="button" class="btn btn-success"
                      data-toggle="modal" data-target="#exampleModalCenter"><i class="fas fa-redo-alt"></i></button>
                      </a>
                    </div>
                    <div class="m-2">
                      <a href="{% url 'todo:delete' todo.id %}">
                      <button type="button" class="btn btn-warning"><i class="fas fa-trash"></i></button>
                      </a>
                    </div>
                    </div>
                    <p>{{todo.date}}</p>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
              
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <h3>Hozirgi vaqt</h3>
        <div class="time"></div>
        <br>
        <a href="https://clck.yandex.ru/redir/dtype=stred/pid=7/cid=1228/*https://yandex.uz/pogoda/10335" target="_blank"><img src="https://info.weather.yandex.net/10335/2_white.ru.png?domain=uz" border="0" alt="Яндекс.Погода"/><img width="1" height="1" src="https://clck.yandex.ru/click/dtype=stred/pid=7/cid=1227/*https://img.yandex.ru/i/pix.gif" alt="" border="0"/></a>
        <div class="clearfix"></div>
        <div class="card mt-3">
          <div class="card-header">
              <h4>Bajarilgan ishlar</h4>
          </div>
          <ul class="list-group">
            {% for todo in doned_todos %}
            {% if todo.done %}
                
            <li class="list-group-item list-group-item-success ">
               <span class="font-italic">{{todo.title}}</span>
             <a href="{% url 'todo:delete' todo.id %}" class="done_delete">
                <button type="button" class="btn btn-warning"><i class="fas fa-trash"></i></button>
                </a>
            </li>
            
            {% endif %}
            {% endfor %}
          
          </ul>
        </div>  
      </div>
    </div>
  </div>
</section>


<script>
  
let clock;

function DisplayTime() { 
  let d = new Date(); 
  let h = d.getHours();
  let m = d.getMinutes(); 
  let s = d.getSeconds();
  let injectTime = `
    <span>${h}</span>
    <span>${m}</span>
    <span>${s}</span>
  `
  document.querySelector(".time").innerHTML = injectTime; 
}

function TimeStart(){
  clock = setInterval("DisplayTime();",1000)
}
function TimeStop(){
  clock = clearInterval(clock)
}
</script>

<style>
  .time{
  margin: 25px 0;
  font-size: 20px;
  font-family: sans-serif;
}
.time span{
  padding: 10px;
  border-radius: 5px;
  background-color: #888;
  color:white;
}
.content{
  display: flex;
  width: 100%;
  height: 80px;
  justify-content: center;
  align-items: center;
}
#add{
  float: right;
}
.done_delete{
  float: right;
}
</style>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add Todo</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="" method="POST">
      <div class="modal-body">
            
              {{addform|crispy}}
              {% csrf_token %}
              
            
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
      </form>
    </div>
  </div>
</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/update.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Update Todo | ID = {{todo.id}}</title>
	    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body onload="TimeStart()">
	<div class="container m-5">
		<div class="row">
			<div class="col-md-8">
				<div class="card">
					<div class="card-header">
						<h3>Update Todo ID = {{todo.id}}</h3>
					</div>
					<div class="card-body">
						<form action="" method="POST">
							{{form|crispy}}
							{% csrf_token %}
							<button type="submit" class="btn btn-primary">Update</button>
						</form>
					</div>
				</div>
			
			</div>
			<div class="col-md-4">
				<div class="card">
					<div class="card-header">
						 <h3>Current time</h3>
					</div>
					<div class="card-body">
				        <div class="time"></div>
				        <br>
				        <a href="https://clck.yandex.ru/redir/dtype=stred/pid=7/cid=1228/*https://yandex.uz/pogoda/10335" target="_blank"><img src="https://info.weather.yandex.net/10335/2_white.ru.png?domain=uz" border="0" alt="Яндекс.Погода"/><img width="1" height="1" src="https://clck.yandex.ru/click/dtype=stred/pid=7/cid=1227/*https://img.yandex.ru/i/pix.gif" alt="" border="0"/></a>
					</div>
				</div>
       
        <div class="clearfix"></div>

			</div>
		</div>
	</div>

<script>
  
let clock;

function DisplayTime() { 
  let d = new Date(); 
  let h = d.getHours();
  let m = d.getMinutes(); 
  let s = d.getSeconds();
  let injectTime = `
    <span>${h}</span>
    <span>${m}</span>
    <span>${s}</span>
  `
  document.querySelector(".time").innerHTML = injectTime; 
}

function TimeStart(){
  clock = setInterval("DisplayTime();",1000)
}
function TimeStop(){
  clock = clearInterval(clock)
}
</script>

<style>
  .time{
  margin: 25px 0;
  font-size: 20px;
  font-family: sans-serif;
}
.time span{
  padding: 10px;
  border-radius: 5px;
  background-color: #888;
  color:white;
}
.content{
  display: flex;
  width: 100%;
  height: 80px;
  justify-content: center;
  align-items: center;
}
#add{
  float: right;
}
.done_delete{
  float: right;
}
</style>

	  <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>